import { MetadataRoute } from "next";

const BASE_URL = "https://filhocuidador.com.br";

const staticPages = [
  "",
  "/artigos",
  "/sobre",
  "/contato",
  "/conselho",
  "/ferramentas",
  "/comunidade",
  "/produtos",
  "/produtos/guia-cuidador-iniciante",
  "/ebooks/como-lidar-pai-alzheimer-agressivo",
  "/metodo",
  "/metodo/fase-1",
  "/metodo/fase-2",
  "/metodo/fase-3",
  "/metodo/fase-4",
  "/metodo/fase-5",
  "/metodo/certificado",
  "/templates",
  "/trabalhe-conosco",
  "/diarios",
  "/pergunte-ao-especialista",
  "/kits",
  "/depoimentos",
  "/videos",
  "/privacidade",
  "/termos",
  "/categorias/entendendo-a-doenca",
  "/categorias/cuidados-praticos",
  "/categorias/saude-emocional",
  "/categorias/juridico",
  "/categorias/familia",
  "/ferramentas/quiz-burnout",
  "/ferramentas/checklist-diagnostico",
  "/ferramentas/calculadora-custos",
];

const diarySlugs = [
  "ana-maria-o-dia-a-dia-com-mae-alzheimer",
  "carlos-cuidar-do-pai-sozinho",
  "mariana-quando-a-familia-nao-ajuda",
  "pedro-o-burnout-que-ninguem-ve",
  "juliana-o-dia-em-que-desisti-e-voltei",
  "roberto-o-avc-que-mudou-tudo",
];

const articleSlugs = [
  "adaptacoes-casa-idoso-seguranca",
  "alimentacao-disfagia-idoso",
  "alzheimer-guia-pratico-cuidador",
  "ansiedade-cuidador-tecnicas-alivio",
  "aposentadoria-idoso-direitos",
  "atividades-estimulacao-cognitiva-idosos-alzheimer",
  "autocuidado-self-care-cuidador",
  "auxilio-doenca-inss-cuidador",
  "avc-recuperacao-cuidados",
  "bpc-loas-guia-completo",
  "burnout-cuidador-sinais-alerta",
  "casamento-relacionamento-cuidando-pai",
  "como-dar-banho-em-idoso-com-alzheimer",
  "como-fazer-procuracao-idoso-alzheimer",
  "como-internar-idoso-demencia",
  "como-lidar-pai-alzheimer-agressivo",
  "comunicacao-idoso-demencia",
  "comunicacao-irmaos-nao-ajudam",
  "cuidador-idoso-burnout-completo",
  "cuidar-de-si-mesmo-enquanto-cuida-outro",
  "culpa-perdao-familia",
  "culpa-raiva-exaustao-normal-sentir",
  "depressao-cuidador-sinais-ajuda",
  "diabetes-idoso-cuidados",
  "dinamica-familiar-mudanca-papeis",
  "direitos-cuidador-idoso-brasil",
  "direitos-idoso-estatuto-lei",
  "dpoc-insuficiencia-respiratoria",
  "filhos-pequenos-cuidar-idoso",
  "gerenciamento-medicamentos-idoso",
  "higiene-banho-seguro-idoso",
  "hipertensao-pressao-alta-idoso",
  "idoso-alzheimer-nao-quer-comer",
  "imposto-renda-deducoes-cuidador",
  "incontinencia-idoso-cuidados",
  "incontinencia-urinaria-idoso-causas",
  "insonia-cuidador-sono-qualidade",
  "insuficiencia-cardiaca-cuidados",
  "interdicao-vs-curatela-qual-usar",
  "isolamento-socializar-cuidador",
  "lidar-mudancas-aceitacao-envelhecimento",
  "limpeza-casa-segura-idoso",
  "luto-perdas-pai-idoso",
  "medicamentos-sus-gratuitos",
  "melhor-fralda-geriatrica-alzheimer",
  "minha-mae-nao-me-reconhece-mais-alzheimer",
  "mobilidade-posicionamento-idoso",
  "noites-seguras-idoso-sono",
  "osteoporose-quedas-prevencao",
  "pai-alzheimer-nao-quer-tomar-banho",
  "parkinson-cuidados-praticos",
  "pensao-morte-direitos-valores",
  "prevencao-quedas-casa-guia-pratico",
  "problemas-visao-catarata-glaucoma",
  "procuracao-idoso-modelo-passo-passo",
  "quando-colocar-asilo-decisao",
  "reconhecendo-burnout-cuidador",
  "relacionamentos-enquanto-cuida",
  "resiliencia-esperanca-cuidador",
  "retorno-trabalho-cuidador",
  "seguranca-lar-idosos-guia-completo",
  "testamento-heranca-guia-pratico",
];

export default function sitemap(): MetadataRoute.Sitemap {
  const staticUrls = staticPages.map((path) => ({
    url: `${BASE_URL}${path}`,
    lastModified: new Date(),
    changeFrequency: "weekly" as const,
    priority: path === "" ? 1.0 : 0.8,
  }));

  const diaryUrls = diarySlugs.map((slug) => ({
    url: `${BASE_URL}/diarios/${slug}`,
    lastModified: new Date(),
    changeFrequency: "monthly" as const,
    priority: 0.7,
  }));

  const articleUrls = articleSlugs.map((slug) => ({
    url: `${BASE_URL}/artigos/${slug}`,
    lastModified: new Date(),
    changeFrequency: "monthly" as const,
    priority: 0.7,
  }));

  return [...staticUrls, ...diaryUrls, ...articleUrls];
}
